name: Create artifact

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Set version for Jar
        run: mvn -B versions:set -DnewVersion="pr-${{ github.event.number }}-${{ github.sha }}" --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: actions/upload-artifact@v2
        with:
          name: origami-editor-jar
          path: target/origami-editor-*.jar