name: Create Pull Request Comment

on:
  workflow_run:
    workflows: [Create artifact]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: console.log(github.payload.workflow_run.pull_requests)
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.payload.workflow_run.event == "pull_request" }}
        with:
          number: github.payload.workflow_run.pull_requests[0].number
          message: |
            Hello #${{ github.event.workflow_run.pull_requests[0].number }} [Latest jar for this branch](https://nightly.link/qurben/origami-editor/actions/runs/${{ github.payload.workflow_run.id }}/origami-editor-jar.zip)