name: Create artifact

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-java11-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-java11-m2

      - name: Set version for Jar
        run: mvn -B versions:set -DnewVersion="pr-${{ github.event.number }}-${{ github.sha }}" --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: actions/upload-artifact@v3
        with:
          name: oriedita-jar
          path: oriedita/target/oriedita-*.jar

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Tests            # Name of the check run which will be created
          path: "*/target/surefire-reports/TEST*.xml"    # Path to test results
          reporter: java-junit        # Format of test results
