name: Create Pull Request Comment

on:
  workflow_run:
    workflows: [Create artifact]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event.workflow_run.pull_requests != [] }}
        with:
          number: ${{ github.event.workflow_run.pull_requests[0] }}
          message: |
            [Latest jar for this branch](https://nightly.link/qurben/origami-editor/actions/runs/${{ github.event.workflow_run.run_id }}/origami-editor-jar.zip)