name: Create Pull Request Comment

on:
  workflow_run:
    workflows: [Create artifact]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.findPr.outputs.number
        with:
          number: ${{ steps.findPr.outputs.pr }}
          message: |
            [Latest jar for this branch](https://nightly.link/qurben/origami-editor/actions/runs/${{ github.event.workflow_run.run_id }}/origami-editor-jar.zip)