name: Release Jar and exe

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  create_jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Set the version
        run: mvn -B versions:set -DnewVersion="${{ steps.get_version.outputs.version-without-v }}" --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/origami-editor-*.jar

  create_executable:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: pwsh

    strategy:
      matrix:
        os:
          - 'windows-latest'
#          - 'ubuntu-20.04'
#          - 'macos-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: maven

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Set the version
        run: mvn -B versions:set -DnewVersion="${{ steps.get_version.outputs.version-without-v }}" --file pom.xml

      - name: Build project and prepare JRE
        run: |
          mvn -B clean package --file pom.xml
          mkdir lib
          mkdir ci-build
          cp target/origami-editor-${{ steps.get_version.outputs.version-without-v }}.jar lib/
          $deps = jdeps --print-module-deps --ignore-missing-deps lib/origami-editor-${{ steps.get_version.outputs.version-without-v }}.jar
          jlink --add-modules $deps --output ci-build/origami-editor-runtime

      - name: Create portable executable
        run: |
          jpackage `
            --type app-image `
            --name "Origami Editor (Portable)" `
            --input lib `
            --dest ci-build `
            --app-version ${{ steps.get_version.outputs.version-without-v }} `
            --main-jar origami-editor-${{ steps.get_version.outputs.version-without-v }}.jar `
            --icon build/logo.ico `
            --runtime-image ci-build/origami-editor-runtime `
            --java-options "'-Dfile.encoding=UTF-8'" `
            --java-options "-Xmx8g" `

      - name: Create zip for portable executable
        uses: papeloto/action-zip@v1
        with:
          files: ci-build/Origami Editor (Portable)
          dest: ci-build/Origami Editor (Portable) ${{ steps.get_version.outputs.version-without-v }}.zip

      - name: Create installer
        run: |
          jpackage `
            --name "Origami Editor" `
            --input lib `
            --dest ci-build `
            --app-version ${{ steps.get_version.outputs.version-without-v }} `
            --main-jar origami-editor-${{ steps.get_version.outputs.version-without-v }}.jar `
            --icon build/logo.ico `
            --file-associations build/FAori.properties `
            --file-associations build/FAcreasepattern.properties `
            --file-associations build/FAorh.properties `
            --license-file LICENSE.md `
            --win-dir-chooser `
            --win-menu `
            --win-shortcut `
            --win-upgrade-uuid 929a6906-b868-4311-9e94-ae469bc5dbd3 `
            --runtime-image ci-build/origami-editor-runtime `
            --java-options "'-Dfile.encoding=UTF-8'" `
            --java-options "-Xmx8g" `

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ci-build/origami-editor-*.exe
            ci-build/Origami Editor*.exe
            ci-build/Origami Editor*.zip
