name: Release Jar and exe

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  create_jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/origami-editor-*.jar

  create_executable:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - 'windows-latest'
#          - 'ubuntu-20.04'
#          - 'macos-latest'

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven

      - name: 'Install makensis (apt)'
        run: sudo apt update && sudo apt install -y nsis nsis-pluginapi
        if: ${{ matrix.os == 'ubuntu-20.04' }}

      - name: 'Install makensis (homebrew)'
        run: brew update && brew install makensis
        if: ${{ matrix.os == 'macos-latest' }}

      - name: 'Set Plugin permissions'
        run: sudo chown -R $(whoami) /usr/share/nsis/Plugins/
        if: ${{ matrix.os == 'ubuntu-20.04' }}

      - name: Build project and prepare JRE
        run: |
          cd build ; ./prepare.ps1

      - name: Create nsis executable
        uses: joncloud/makensis-action@v3.3
        with:
          script-file: build/portable.nsi

      - name: Create nsis installer
        uses: joncloud/makensis-action@v3.3
        with:
          script-file: build/installer.nsi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/origami-editor-*.exe
