name: Release Jar and exe

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  create_jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/origami-editor-*.jar

  create_executable:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: pwsh

    strategy:
      matrix:
        os:
          - 'windows-latest'
#          - 'ubuntu-20.04'
#          - 'macos-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Get the version
        id: mvn_version
        run: |
          echo "::set-output name=version::$(mvn -B help:evaluate -D"expression=project.version" -q -D"forceStdout" --file pom.xml)"

      - name: Build project and prepare JRE
        run: |
          mvn -B clean package --file pom.xml
          mkdir lib
          mkdir out
          cp target/origami-editor-${{ steps.mvn_version.outputs.version }}.jar lib/

      - name: Create portable executable
        run: |
          jpackage `
            --type app-image `
            --name origami-editor `
            --input lib `
            --dest ci-build `
            --app-version ${{ steps.mvn_version.outputs.version }} `
            --main-jar origami-editor-${{ steps.mvn_version.outputs.version }}.jar `
            --icon build/logo.ico `
            --java-options Xmx8g `
            --java-options '-Dfile.encoding="UTF-8"' `

      - name: Create zip for portable executable
        uses: papeloto/action-zip@v1
        with:
          files: ci-build/origami-editor
          dest: ci-build/origami-editor-portable-${{ steps.mvn_version.outputs.version}}.zip

      - name: Create installer
        run: |
          jpackage `
            --name origami-editor `
            --input lib `
            --dest ci-build `
            --app-version ${{ steps.mvn_version.outputs.version }} `
            --main-jar origami-editor-${{ steps.mvn_version.outputs.version }}.jar `
            --icon build/logo.ico `
            --file-associations build/FAori.properties `
            --license-file LICENSE.md `
            --win-dir-chooser `
            --win-menu `
            --win-shortcut `
            --java-options Xmx8g `
            --java-options '-Dfile.encoding="UTF-8"' `


      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ci-build/origami-editor-*.exe
            ci-build/origami-editor-portable-*.zip
