name: Release Jar and exe

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  create_jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Set the version
        run: mvn -B versions:set -DnewVersion="${{ steps.get_version.outputs.version-without-v }}" --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/oriedita-*.jar

  create_executable:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: pwsh

    strategy:
      matrix:
        os:
          - 'windows-latest'
#          - 'ubuntu-20.04'
#          - 'macos-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: maven

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Set the version
        run: mvn -B versions:set -DnewVersion="${{ steps.get_version.outputs.version-without-v }}" --file pom.xml

      - name: Build project and prepare JRE
        run: |
          mvn -B clean package --file pom.xml
          mkdir lib
          mkdir ci-build
          cp oriedita/target/oriedita-${{ steps.get_version.outputs.version-without-v }}.jar lib/
          $deps = jdeps --print-module-deps --ignore-missing-deps lib/oriedita-${{ steps.get_version.outputs.version-without-v }}.jar
          jlink --add-modules $deps --output ci-build/oriedita-runtime

      - name: Create portable executable
        run: |
          jpackage `
            @build/jpackage-common-args `
            --type app-image `
            --name "Oriedita-Portable-${{ steps.get_version.outputs.version-without-v }}" `
            --app-version ${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }} `
            --main-jar oriedita-${{ steps.get_version.outputs.version-without-v }}.jar `

      - name: Create zip for portable executable
        uses: papeloto/action-zip@v1
        with:
          files: 'ci-build/Oriedita-Portable-${{ steps.get_version.outputs.version-without-v }}'
          dest: ci-build/Oriedita-Portable-${{ steps.get_version.outputs.version-without-v }}.zip

      - name: Create installer
        run: |
          jpackage `
            @build/jpackage-common-args `
            @build/jpackage-installer-args `
            --name "Oriedita" `
            --app-version ${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }} `
            --main-jar oriedita-${{ steps.get_version.outputs.version-without-v }}.jar `

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ci-build/oriedita-*.exe
            ci-build/Oriedita*.exe
            ci-build/Oriedita*.zip
